<a href="https://colab.research.google.com/github/zinzisibanyoni850-max/Zinzi_portfolio/blob/main/cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/Sales_table.csv")

In [ ]:
df.head()

,Maker,Genmodel,Genmodel_ID,2020,2019,2018,2017,2016,2015,2014,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
0,ABARTH,ABARTH 124,2_1,0,19,27,60,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ABARTH,ABARTH 500,2_2,0,0,1,2,66,717,762,...,915,766,0,0,0,0,0,0,0,0
2,ABARTH,ABARTH 595,2_4,2144,2866,3907,3295,3132,1612,516,...,0,0,0,0,0,0,0,0,0,0
3,ABARTH,ABARTH 695,2_6,45,65,270,114,29,10,14,...,0,0,0,0,0,0,0,0,0,0
4,ABARTH,ABARTH PUNTO,2_9,0,0,0,0,0,0,56,...,97,172,74,0,0,0,0,0,0,0

In [ ]:
df.tail()

,Maker,Genmodel,Genmodel_ID,2020,2019,2018,2017,2016,2015,2014,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
768,VOLVO,VOLVO XC40,96_20,24281,14894,6616,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
769,VOLVO,VOLVO XC60,96_16,7694,11182,10840,14994,14808,12830,9102,...,4548,3373,308,0,0,0,0,0,0,0
770,VOLVO,VOLVO XC70,96_17,0,0,0,17,1006,1586,1710,...,1447,1067,1059,1423,1347,1524,963,626,119,0
771,VOLVO,VOLVO XC90,96_18,4969,7495,6475,5564,5254,2756,2319,...,6392,3633,1879,3232,3547,4614,3901,1507,0,0
772,ZENOS,ZENOS E10,99_1,0,0,0,2,10,7,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
display(df)

,Maker,Genmodel,Genmodel_ID,2020,2019,2018,2017,2016,2015,2014,...,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
0,ABARTH,ABARTH 124,2_1,0,19,27,60,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,ABARTH,ABARTH 500,2_2,0,0,1,2,66,717,762,...,915,766,0,0,0,0,0,0,0,0
2,ABARTH,ABARTH 595,2_4,2144,2866,3907,3295,3132,1612,516,...,0,0,0,0,0,0,0,0,0,0
3,ABARTH,ABARTH 695,2_6,45,65,270,114,29,10,14,...,0,0,0,0,0,0,0,0,0,0
4,ABARTH,ABARTH PUNTO,2_9,0,0,0,0,0,0,56,...,97,172,74,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,VOLVO,VOLVO XC40,96_20,24281,14894,6616,8,0,0,0,...,0,0,0,0,0,0,0,0,0,0
769,VOLVO,VOLVO XC60,96_16,7694,11182,10840,14994,14808,12830,9102,...,4548,3373,308,0,0,0,0,0,0,0
770,VOLVO,VOLVO XC70,96_17,0,0,0,17,1006,1586,1710,...,1447,1067,1059,1423,1347,1524,963,626,119,0
771,VOLVO,VOLVO XC90,96_18,4969,7495,6475,5564,5254,2756,2319,...,6392,3633,1879,3232,3547,4614,3901,1507,0,0
772,ZENOS,ZENOS E10,99_1,0,0,0,2,10,7,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
df.shape

(773, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 773 entries, 0 to 772
Data columns (total 23 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Maker        773 non-null    object
 1   Genmodel     773 non-null    object
 2   Genmodel_ID  773 non-null    object
 3   2020         773 non-null    int64
 4   2019         773 non-null    int64
 5   2018         773 non-null    int64
 6   2017         773 non-null    int64
 7   2016         773 non-null    int64
 8   2015         773 non-null    int64
 9   2014         773 non-null    int64
 10  2013         773 non-null    int64
 11  2012         773 non-null    int64
 12  2011         773 non-null    int64
 13  2010         773 non-null    int64
 14  2009         773 non-null    int64
 15  2008         773 non-null    int64
 16  2007         773 non-null    int64
 17  2006         773 non-null    int64
 18  2005         773 non-null    int64
 19  2004         773 non-null    int64
 20  2003         773 non-null    int64
 21  2002         773 non-null    int64
 22  2001         773 non-null    int64
dtypes: int64(20), object(3)
memory usage: 139.0+ KB

In [ ]:
df.describe()

,2020,2019,2018,2017,2016,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,2005,2004,2003,2002,2001
count,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000
mean,1979.454075,2818.445019,2862.076326,2963.058215,3203.897801,3132.236740,2915.015524,2628.974127,2314.923674,2131.992238,2165.604140,2041.534282,1941.636481,1976.517464,1626.055627,1325.930142,1058.534282,805.106080,564.614489,349.142303
std,5403.526805,7466.655137,7731.051191,8199.212870,9234.009443,9571.845809,9085.533712,8520.582424,7742.340436,7122.691281,7249.633197,7136.761258,6755.753065,6958.049764,5690.905348,4616.839607,3683.193277,2989.763318,2200.688401,1342.884560
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,1.000000,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,794.000000,1440.000000,1427.000000,1437.000000,1392.000000,1287.000000,946.000000,846.000000,684.000000,612.000000,674.000000,602.000000,560.000000,550.000000,480.000000,418.000000,224.000000,106.000000,62.000000,36.000000
max,46739.000000,74500.000000,89564.000000,87409.000000,113568.000000,125619.000000,122815.000000,113390.000000,100228.000000,87266.000000,91353.000000,100975.000000,73429.000000,77257.000000,68079.000000,58824.000000,43404.000000,32345.000000,26767.000000,15737.000000